### PR TITLE
Collated Codes

### PR DESCRIPTION
**Pull request by ChaseTiong**
This is my collated codes for submission for V0.5. Please do help me delete the old one if you guys do collate and found any.

Or if you guys find any codes that is written by you guys, please inform me so I can make the changes. However, do let me know earlier like anytime before 10pm.

### CODE REVIEW

**Comment by louietyj** [comment]
Hi Yaocong, please check through your unused collates. We have found a lot of code in there that are trivial reuses of existing code by us. For example, all your fixtures were directly plagiarized from us with insignificant modifications of names and dates. The entire structure is so similar that it looks copy-pasted.

In the spirit of DRY, within an internal project we always encourage code reuse and we have been quite generous about claiming reused with modifications code. But when you decide to fork from our repo, it is not fair to continue reusing our code and claiming it as "unused" when it is clear that these are about 90% derivative of our existing work.

Irvin and I think that it would be fair for you to mark these chunks as "reused".

**Comment by ChaseTiong** [comment]
@louietyj I have recollate unused files with the variables to be reuse

**Comment by ChaseTiong** [comment]
Let me know if there are any part that require changes. Thank you

**Comment by irvinlim** [comment]
Will be taking the unused/reused files, the others will be recollated.

**Pull request merged**
