### PR TITLE
Rewrite list controller

### PR DESCRIPTION
**Pull request by irvinlim**
Initial rewrite

### CODE REVIEW

**Comment by louietyj** [comment]
We'll standardize List and ClearControllers... one day.

At least this looks so much better than it was 2 hours ago.

**Review by louietyj — APPROVED** [review]
We'll standardize List and ClearControllers... one day.

At least this looks so much better than it was 2 hours ago.

**Comment by irvinlim** [comment]
Yup, but I think don't really need to standardize, the logic is the same la

**Comment by louietyj** [comment]
Looks neater only, that's all lor

**Pull request merged**
