### PR TITLE
Fix ordering of Tasks loaded by changing HashSet to ArrayList

### LINKED ISSUE #22: Sorting problem
There are some sorting and display issues.
For e.g. 
`add test1 by today`
`add test2 by today`

After exiting the application and relaunch it, the ordering of the tasks will be different.

### PR DESCRIPTION
**Pull request by irvinlim**
Fixes #22.

@louietyj Does this break anything?

### CODE REVIEW

**Comment by louietyj** [comment]
I'm not keen on turning this into an ArrayList because we need to support a large number of records, and deleting something at the start means the whole list of records needs to move. That's why HashSet.

The solution to #22 should be a smarter comparator that imposes a total ordering, i.e. sort by date, then sort by type, then sort by time.

**Comment by irvinlim** [comment]
We are using comparator for most items, only items without a date (i.e. floating tasks) will suffer from the lack of sorting. I agree that a HashSet is more efficient than ArrayList, but would other kinds of data structures work that still maintain ordering work? E.g. `LinkedHashSet`, `LinkedList`

**Comment by louietyj** [comment]
LinkedList will cause destroy to be O(n) which is bad. I think LinkedHashSet is okay and solves our problems.

**Comment by irvinlim** [comment]
@louietyj LinkedHashSet didn't work, seems like it must be a List for it to work. How does using a LinkedList make destroy become O(n)?

**Comment by louietyj** [comment]
Because destroying an object in the list requires a linear search for it, unless we do some complicated indexing.

**Comment by louietyj** [comment]
Which I don't want to do for an SE project (:

**Comment by louietyj** [comment]
Btw I think the reason LinkedHashSet doesn't work is because it only guarantees the ordering for that particular instance in memory. Once you serialize and deserialize it, all bets are off LOL

**Pull request merged**
