### PR TITLE
Events model

### LINKED ISSUE #18: Events model

### PR DESCRIPTION
**Pull request by louietyj**
Fixes #18

### CODE REVIEW

**Comment by louietyj** [comment]
@irvinlim need a front-end API to show events too (:

**Comment by irvinlim** [comment]
For events, I don't think we should use the "by" keyword as a delimiter; instead we should have "on", and "from"/"to". I know that this parser is just temporary, so just keep it in mind while we merge this.

We'll need to work out how it distinguishes tasks and events from natural language.

**Comment by louietyj** [comment]
My current intention is to have a "tokenizer" concern, so each controller can declare some tokens and tell the tokenizer to go through the input and return the fields. The controller will have to do some preparatory work esp. with dates that may not have a token associated. Bottomline is the input values can even be out of order as long as we can figure out the tokens.

Let's wait for [this girl](https://ivle.nus.edu.sg/v1/forum/board_read.aspx?forumid=5b7a6f75-58ed-4922-b8b0-ca761d166a6a&postid=d082b258-4350-45e7-8e26-7ff53538aeea&lpreferrer=&headingid=5d7d5e65-fba5-4876-a902-ed71d938a515&isNested=1) though, she seems to have found some magic library that she doesn't want to share :(

**Comment by irvinlim** [comment]
@louietyj Is this okay to merge?

**Pull request merged**
